### ISSUE TITLE
Is writing MIDIs to WAV/MP3 a possiblity later down the line?

### ISSUE THREAD

**Issue by sirbaratusii** [skjelten/emusc#30]
I know this is pretty early to ask but how possible is it to implement a feature that outputs the MIDI playback to .WAV and other formats? I ask because whenever I do livestreams or make videos, I tend to batch convert them to MP3s for easier playback. I would've recorded all of the MIDIs but that would take a long time.

Also nice to see a emulator for the SC-55 being developed btw.

**Comment by skjelten** [comment]
WAV-output is something I had earlier when I needed to dump all the instrument samples for debugging. I don't think it's that much work to add wav-output as a new audio output option.

That being said, just keep in mind that EmuSC is far from being good enough to do proper audio emulation of the SC-55. You are still better off using TiMidity / fluidsynth and the [SC55_Soundfont](https://github.com/Kitrinx/SC55_Soundfont).

**Comment by skjelten** [comment]
Just FYI: Support for WAV audio output to file was added a while ago. It is a bit crude, not very well tested, but should do the trick when output to file is desired.

Closing this issue since we have a solution for writing audio to disk, but feel free to add comments if you have any issues in getting it to work.
