### ISSUE TITLE
MacOS build succeedes, but emusc.app is missing executable

### ISSUE THREAD

**Issue by dagjomar** [skjelten/emusc#33]
After running 
```
cmake . -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5
```

The command succeed with output
```
-- 
--  EmuSC client interface summary: 
-- -===============================-
-- 
-- Platform: macOS
--  * Build bundle: 
-- 
-- Qt version: Qt5
-- 
-- Audio APIs:
--  * ALSA  : no
--  * Core  : yes
--  * Jack  : no
--  * Null  : yes
--  * Pulse : no
--  * Qt    : yes
--  * WAV   : yes
--  * Win32 : no
-- 
-- MIDI APIs:
--  * ALSA  : no
--  * Core  : yes
--  * Win32 : no
-- 
-- Make sure all needed APIs are found before you continue
-- 
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/djmusic/PROJECTS/EMUSC/emusc/emusc
```

But then when running
```
open src/emusc.ap
```

The error is:
```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=4129, _LSFunction=_LSOpenStuffCallLocal}
```

And if I try to read the contents of the bundle, I find that the Contents/MacOS folder is empty
```
ls src/emusc.app/Contents/MacOS
```

Any ideas?

**Comment by skjelten** [comment]
Did the compile command complete successfully?

The reason why I am asking is that I just tried to build updated git master on a Mac with qt5 (same setup as yours) and the compilation failed due to a missing header file. I just committed a fix for that, so please try a git pull and recompile to see if that fixes the issue.

**Comment by dagjomar** [comment]
Yes, the compile command completed successfully (as far as I could tell)
See the output above, no error output as I can see.

Pulled latest now and recompiled the lib and also emusc app but same issue with missing executable in the emusc.app bundle.

<img width="243" alt="Screenshot 2024-03-10 at 12 49 30" src="https://github.com/skjelten/emusc/assets/416408/9c87c90f-5066-468c-a425-9f0d5a474969">

**Comment by dagjomar** [comment]
Am I supposed to run the command `make` in the emusc folder?

Because that seems to fail at least
```
[ 89%] Building CXX object src/CMakeFiles/emusc-client.dir/scene.cc.o
[ 92%] Building CXX object src/CMakeFiles/emusc-client.dir/synth_dialog.cc.o
[ 96%] Building CXX object src/CMakeFiles/emusc-client.dir/emusc-client_autogen/DQCCZ5YITF/qrc_emusc.cpp.o
[100%] Linking CXX executable emusc.app/Contents/MacOS/emusc
ld: library not found for -lemusc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/emusc.app/Contents/MacOS/emusc] Error 1
make[1]: *** [src/CMakeFiles/emusc-client.dir/all] Error 2
make: *** [all] Error 2
```

I did not see this command in the readme instructions so expected things to work by just doing `cmake . ` command

**Comment by skjelten** [comment]
Ok, the problem seems quite apparent then. The reason why you get this linker failure is most likely because you have not built the library yet. I can see that the README file is a bit short on MacOS for emusc (the README for libemusc has some more details). But the short explanation is that after using `cmake` to create the Makefiles you also need to compile the source code into a binary by using `make`.

If you go to the emusc root directory and run `make`  it will automatically enter libemusc and compile the library and then enter emusc and compile the application. Or you can manually enter emusc/libemusc and emusc/emusc and run `make` in each directory (make sure to compile the library first). This should successfully compile the application and create the bundle for you.

**Comment by dagjomar** [comment]
I believe I have done those steps, but in the individual folders. I was not aware I could run stuff from the root folder.

Trying that now, and noting down the individual steps here:

```
git clone https://github.com/skjelten/emusc.git

cd emusc

cmake .

make

open emusc/src/emusc.app 
```

Success! This worked perfectly.
(Note: Before these commands, I have previously added some env exports of the QT stuff, and also added it to the path)

<img width="522" alt="Screenshot 2024-03-10 at 13 44 46" src="https://github.com/skjelten/emusc/assets/416408/45877c09-8b26-48bd-81da-a66a090e68a8">


Thanks for the help.

Before closing this issue, I would recommend updating the root README to mention that it's possible to compile and run everything from the root folder and not go into each folder and read each readme, like I did first.
