### ISSUE TITLE
Crash on macOS using Qt audio

### ISSUE THREAD

**Issue by mmontag** [skjelten/emusc#46]
Hi, I selected Qt audio engine instead of Core Audio and then emusc.app started crashing on startup. 

I found where `QSettings` stores preferences (~/Library/Preferences/com.emusc.EmuSC.plist) and removed the `Audio.system` value. Also on macOS, you have to run `killall -u $USER cfprefsd` to prevent the plist from being cached.  

Maybe add this tip to troubleshooting section.

**Comment by skjelten** [comment]
Yes, that is a good point. There should be some documentation on how to edit the configuration manually if it crashes emusc upon startup. To make things worse, Linux, macOS and Windows all have completely different backends to QT's Settings class.

I just added a command line option to start in "power off" mode, so that would at least help users who can run emusc from the command line.

**Comment by skjelten** [comment]
Closing this issue as we now have some information about how to work around such issues in the wiki.

https://github.com/skjelten/emusc/wiki/Troubleshooting-Guide
