### ISSUE TITLE
Mk1 'ooh' sound broken.

### ISSUE THREAD

**Issue by ThatRetroGuy** [skjelten/emusc#51]
Hello!!  after seeing this amazing compile and gotten it to work with the mk 1 rom.
the 'ooh' bank seem to play every sound in the rom.

https://github.com/skjelten/emusc/assets/76837099/a5984eb3-2e2c-4a9d-b8b5-640107fde61f

**Comment by Grieferus** [comment]
What ROMs do you use?

**Comment by ThatRetroGuy** [comment]
im using the mk 1 roms and its the falcosoft player.

**Comment by Grieferus** [comment]
Doesn't seem to be broken on my part. But I did notice that your EmuSC shows Clarinet as selected instrument, while FSMP shows Voice Oohs as selected instrument.

**Comment by ThatRetroGuy** [comment]
thats the first channel displaying with the clarinet and im playing the channel seperate in the midi player..

**Comment by Grieferus** [comment]
Still, doesn't seem to be broken for me. Are you sure it's mk1 ROMs and not mk2?

**Comment by ThatRetroGuy** [comment]
for some reason very recently, the sound seem to have fixed itself??  


![Skærmbillede 2024-04-08 035848](https://github.com/skjelten/emusc/assets/76837099/c2f71b8f-8d1e-48fa-9c83-e800f24401ec)

**Comment by skjelten** [comment]
It seems like emusc plays the wrong instrument (and therefore with the wrong pitch corrections). I have noticed this behavior in two different scenarios:
* If the control ROM and the PCM ROMs are not from the same set. Meaning that the control ROM is not compatible with the PCM ROMs, e.g. using the SC-55 control ROM with SC-55mkII PCM ROMs. This should not be that of an issue anymore since the SHA256 verification of the ROM files is supposed to prevent this mistake.
* In certain situations when the SC-55mkII ROMs are used

Did you change the ROM configuration before the audio issue fixed itself, or is the screenshot showing the ROM configuration you used both before and after the issue disappeared?

**Comment by ThatRetroGuy** [comment]
ive made sure each rom are in their own folder, and yeah this is like the config it had when did that glitchy sound, but it seems to have oddly fixed itself, not doing it anymore.

**Comment by Karmeck** [comment]
> ive made sure each rom are in their own folder, and yeah this is like the config it had when did that glitchy sound, but it seems to have oddly fixed itself, not doing it anymore, so im just waiting to see whats gonna happen with the next compile of this emulator if it fixes the crunchy sound and detuning.

you recently had an other issue closed. I believe I can help you with that. I'm at vogons, same name.

**Comment by skjelten** [comment]
Ok, I will close this ticket with a few comments:
* The crunchy sound I believe is due to the lack of interpolation when changing sample rate / pitch. This is on the roadmap for v0.2.0.
* The detuning (if you are referring #50)  to is a bug that I hope we will be able to fix sooner
* If you experience the same problem again, please reopen this issue
